"""Generates JSON and Markdown status reports for humans and Hermes."""

import datetime
import json
from pathlib import Path
from typing import Any, Dict, List, Optional


def generate_markdown_report(
    accounts_status: List[Dict[str, Any]],
    output_path: str = "docs/account-status.md",
) -> str:
    """Generate docs/account-status.md report."""
    now_str = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# Antigravity Account Status",
        "",
        f"Updated: {now_str}",
        "",
        "| Account | Gemini | Claude | Status | Cooldown |",
        "| :--- | :---: | :---: | :--- | :--- |",
    ]

    for acc in accounts_status:
        acc_name = acc.get("display_name") or acc.get("account_id") or "unknown"
        gemini_q = acc.get("gemini_quota_str", "unknown")
        claude_q = acc.get("claude_quota_str", "unknown")
        status = acc.get("health_status", "healthy")
        cooldown = acc.get("cooldown_str", "none")
        lines.append(f"| {acc_name} | {gemini_q} | {claude_q} | {status} | {cooldown} |")

    lines.append("")
    lines.append("> Auto-generated by Antigravity Gateway Quota Monitor.")
    report_content = "\n".join(lines)

    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        f.write(report_content)

    return report_content


def save_quota_state_json(
    data: Dict[str, Any],
    output_path: str = "data/quota-state.json",
) -> None:
    """Save latest parsed quota snapshot as JSON."""
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, default=str)
